apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lectern.fullname" . }}
  labels:
{{ include "lectern.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "lectern.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "lectern.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "lectern.fullname" . }}
    {{- with .Values.podSecurityContext }}
      securityContext:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: PORT
            value: {{ .Values.appConfig.port | quote }}
          - name: MONGO_HOST
            value: {{ .Values.appConfig.mongoHost | quote }}
          - name: MONGO_PORT
            value: {{ .Values.appConfig.mongoPort | quote }}
          - name: MONGO_USER
            value: {{ .Values.appConfig.mongoUser | quote }}
          - name: MONGO_PASS
            value: {{ .Values.appConfig.mongoPass | quote }}
          - name: AUTH_ENABLED
            value: {{ .Values.appConfig.authEnabled | quote }}
          - name: EGO_API
            value: {{ .Values.appConfig.egoApi | quote }}
          - name: SCOPE
            value: {{ .Values.appConfig.scope | quote }}
{{- if .Values.extraEnv }}
  {{ range $key, $value := .Values.extraEnv }}
          - name: {{ $key }}
            value: {{ $value | quote }}
  {{- end }}
{{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.appConfig.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
