# Default values for maestro.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: overture/maestro
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 11235

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: maestro.local
      paths: []
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

extraEnv: {}

appVolume:
  size: 1Gi
  storageClass: standard
  mountPath: /app-data

containerPort: 80