# Default values for maestro.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/overture-stack/maestro
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 11235
  portName: http

ingress:
  # annotations:
  #   cert-manager.io/cluster-issuer: letsencrypt
  # className: private
  enabled: false
  hosts:
    - host: maestro.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  # tls:
  #   - hosts:
  #     - maestro.local
  #     secretName: maestro.local

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

# use this to inject all the env vars you need to override application.yaml
# see _examples/provide-env/values.yaml
extraEnv: {}

extraEnvYaml: []
# - name: ELASTIC_USER
#   valueFrom:
#     secretKeyRef:
#       name: secret-name
#       key: secret-key

# this is useful to integrate with vault 
rbac:
  create:
    tokenReview: false

appVolume:
  mountPath: /app/app-data

containerPort: 11235
