apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ego.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ego.name" . }}
    helm.sh/chart: {{ include "ego.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ego.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ego.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "ego.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SERVER_PORT
              value: "8081"
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.appConfig.activeProfiles }}
            - name: GOOGLE_CLIENT_CLIENTID
              value: {{ .Values.appConfig.googleClientID }}
            - name: GOOGLE_CLIENT_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "ego.fullname" . }}
                  key: google-client-secret
            - name: GOOGLE_CLIENT_PREESTABLISHEDREDIRECTURI
              value: "https://{{ .Values.appConfig.host }}/api/oauth/login/google"
            - name: ORCID_CLIENT_CLIENTID
              value: {{ .Values.appConfig.orcidClientID }}
            - name: ORCID_CLIENT_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "ego.fullname" . }}
                  key: orcid-client-secret
            - name: ORCID_CLIENT_PREESTABLISHEDREDIRECTURI
              value: "https://{{ .Values.appConfig.host }}/api/oauth/login/orcid"
            - name: LINKEDIN_CLIENT_CLIENTID
              value: {{ .Values.appConfig.linkedInClientID }}
            - name: LINKEDIN_CLIENT_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "ego.fullname" . }}
                  key: linkedin-client-secret
            - name: LINKEDIN_CLIENT_PREESTABLISHEDREDIRECTURI
              value: "https://{{ .Values.appConfig.host }}/api/oauth/login/linkedin"
            - name: GITHUB_CLIENT_CLIENTID
              value: {{ .Values.appConfig.githubClientID }}
            - name: GITHUB_CLIENT_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "ego.fullname" . }}
                  key: github-client-secret
            - name: GITHUB_CLIENT_PREESTABLISHEDREDIRECTURI
            - name: FACEBOOK_CLIENT_CLIENTID
              value: {{ .Values.appConfig.facebookClientID | quote }}
            - name: FACEBOOK_CLIENT_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "ego.fullname" . }}
                  key: facebook-client-secret
            - name: FACEBOOK_CLIENT_PREESTABLISHEDREDIRECTURI
              value: "https://{{ .Values.appConfig.host }}/api/oauth/login/facebook"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "ego.fullname" . }}-postgres
                  key: postgres-password
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://{{ template "ego.fullname" . }}-postgres:5432/{{ .Values.postgres.postgresDb }}?stringtype=unspecified"
            - name: SPRING_FLYWAY_ENABLED
              value: "true"
            - name: SPRING_FLYWAY_LOCATIONS
              value: "classpath:flyway/sql,classpath:db/migration"
            - name: SPRING_FLYWAY_PLACEHOLDERS_DEFAULT-PROVIDER
              value: {{ .Values.appConfig.defaultProvider }}
            - name: SWAGGER_HOST
              value: {{ .Values.appConfig.swaggerHost }}
            - name: SWAGGER_BASEURL
              value: {{ .Values.appConfig.swaggerBaseUrl }}
            - name: APITOKEN_DURATIONDAYS
              value: {{ .Values.appConfig.apiTokenDurationDays | quote }}
            - name: JWT_USER_DURATIONMS
              value: {{ .Values.appConfig.jwt.userDurationMs | quote }}
            - name: JWT_APP_DURATIONMS
              value: {{ .Values.appConfig.jwt.appDurationMs | quote }}
            - name: REFRESHTOKEN_DURATIONMS
              value: {{ .Values.appConfig.refreshToken.durationMs | quote }}
            - name: REFRESHTOKEN_COOKIEISSECURE
              value: {{ .Values.appConfig.refreshToken.cookieIsSecure | quote }}
            - name: REFRESHTOKEN_DOMAIN
              value: {{ .Values.appConfig.host }}
{{- if .Values.extraEnv }}
  {{ range $key, $value := .Values.extraEnv }}
            - name: {{ $key }}
              value: {{ $value | quote }}
  {{- end }}
{{- end }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
            - name: grpc
              containerPort: 50051
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
        - name: {{ .Chart.Name }}-ui
          image: "{{ .Values.uiImage.repository }}:{{ .Values.uiImage.tag }}"
          imagePullPolicy: {{ .Values.uiImage.pullPolicy }}
          env:
            - name: REACT_APP_API
              value: "https://{{ .Values.appConfig.host }}/api"
            - name: REACT_APP_EGO_CLIENT_ID
              value: {{ .Values.appConfig.egoClientId }}
            - name: REACT_APP_KEYCLOAK_ENABLED
              value: {{ .Values.appConfig.uiKeycloakEnabled }}
          ports:
            - name: http-ui
              containerPort: 8080
              protocol: TCP
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
