{{- if .Values.ingressUi.enabled -}}
{{- $fullName := include "ego.fullname" . -}}
{{- if semverCompare ">=1.19" .Capabilities.KubeVersion.Version -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14" .Capabilities.KubeVersion.Version }}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-ui
  labels:
    app.kubernetes.io/name: {{ include "ego.name" . }}
    helm.sh/chart: {{ include "ego.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.ingressUi.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  {{- if and .Values.ingressUi.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.Version) }}
  ingressClassName: {{ .Values.ingressUi.className }}
  {{- end }}
  {{- if .Values.ingressUi.tls }}
  tls:
  {{- range .Values.ingressUi.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingressUi.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: http-ui
  {{- end }}
