apiVersion: v1
kind: Secret
metadata:
  name: {{ include "song.fullname" . }}
  labels:
    app: {{ include "song.name" . }}
    chart: {{ include "song.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
{{- if .Values.backup.enabled }}
  s3-secretKey: {{ .Values.backup.s3.secretKey | b64enc | quote }}
{{- end }}
  id-authtoken: {{ .Values.appConfig.id.federated.auth.bearer.token | b64enc | quote }}
  score-accessToken: {{ .Values.appConfig.score.accessToken | b64enc | quote }}
  score-clientCredentials-secret: {{ .Values.appConfig.score.clientCredentials.secret | b64enc | quote }}
  auth-server-client-secret: {{ .Values.appConfig.auth.server.clientSecret | b64enc | quote }}
