apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lyric.fullname" . }}
  labels:
{{ include "lyric.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "lyric.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "lyric.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "lyric.fullname" . }}
    {{- with .Values.podSecurityContext }}
      securityContext:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: DB_HOST
            value: {{ .Values.appConfig.dbHost | quote }}
          - name: DB_NAME
            value: {{ .Values.appConfig.dbName | quote }}
          - name: DB_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: {{ template "lyric.fullname" . }}
                  key: db-password
          - name: DB_PORT
            value: {{ .Values.appConfig.dbPort | quote }}
          - name: DB_USER
            value: {{ .Values.appConfig.dbUser | quote }}
          - name: ID_CUSTOM_ALPHABET
            value: {{ .Values.appConfig.idCustomAlphabet | quote }}
          - name: ID_CUSTOM_SIZE
            value: {{ .Values.appConfig.idCustomSize | quote }}
          - name: ID_USELOCAL
            value: {{ .Values.appConfig.idUseLocal | quote }}
          - name: LECTERN_URL
            value: {{ .Values.appConfig.lecternUrl | quote }}
          - name: LOG_LEVEL
            value: {{ .Values.appConfig.logLevel | quote }}
          - name: PORT
            value: {{ .Values.appConfig.port | quote }}
          - name: UPLOAD_LIMIT
            value: {{ .Values.appConfig.uploadLimit | quote }}
{{- if .Values.extraEnv }}
  {{ range $key, $value := .Values.extraEnv }}
          - name: {{ $key }}
            value: {{ $value | quote }}
  {{- end }}
{{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.appConfig.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
