apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lyric.fullname" . }}
  labels:
    app: {{ include "lyric.name" . }}
    chart: {{ include "lyric.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  db-password: {{ .Values.appConfig.dbPassword | b64enc | quote }}
