# Default values for rollcall.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/overture-stack/rollcall
  tag: edge
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  portName: http

ingress:
  # annotations:
  #   cert-manager.io/cluster-issuer: letsencrypt
  # className: private
  enabled: false
  hosts:
    - host: rollcall.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  # tls:
  #   - hosts:
  #     - rollcall.local
  #     secretName: rollcall.local


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

appConfig:
  SPRING_PROFILES_ACTIVE: test
  SERVER_PORT: 9001
  ELASTICSEARCH_HOST: http://localhost
  ELASTICSEARCH_PORT: 9200
  ROLLCALL_ALIASES_0_ALIAS: data_centric
  ROLLCALL_ALIASES_0_ENTITY: data
  ROLLCALL_ALIASES_0_TYPE: centric

podSecurityContext:
  runAsGroup: 9999
  runAsNonRoot: true
  runAsUser: 9999

# choose rbac roles to enable
rbac:
  create:
    # for vault kubernetes integration
    tokenReview: false

