# Default values for Arranger.
affinity: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

config:
  documentType: ""
  es:
    host: "http://elasticsearch:9200"
    password:
      secretName: ""
    username: "" #If empty or not defined, ES configured without auth
  index: ""
  port: 5050

fullnameOverride: ""

image:
  repository: ghcr.io/overture-stack/arranger-server
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []

ingress:
  enabled: false
  # annotations:
  #   cert-manager.io/cluster-issuer: letsencrypt
  # className: private
  hosts:
    - host: arranger-server.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - arranger-server.local
      secretName: arranger-server.local

nameOverride: ""

nodeSelector: {}

podAnnotations: {}

podSecurityContext:
  runAsGroup: 9999
  runAsNonRoot: true
  runAsUser: 9999

replicaCount: 1

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

serverConfigs:
  baseConfigs: "{}"
  extendedConfigs: "{}"
  facetsConfigs: "{}"
  matchboxConfigs: "{}"
  tableConfigs: "{}"

service:
  type: ClusterIP
  port: 80
  portName: arranger-server
  uiPort: 81
  uiPortName: arranger-ui

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

tolerations: []

####################
# To be deprecated
####################

apiConfig:
  es:
    host: ""
    password:
      secretName: ""
    username: ""
  port: ""

apiImage:
  pullPolicy: ""
  repository: ""
  tag: ""

apiIngress: {}

uiImage:
  repository: ghcr.io/overture-stack/arranger-ui
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

uiConfig:
  enabled: false
  serverUrl: https://arranger-server.local/api
  port: 8080
  ReactAppBaseURL: ""

uiIngress:
  enabled: false
  # annotations:
  #   cert-manager.io/cluster-issuer: letsencrypt
  # className: private
  hosts:
    - host: arranger-ui.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - arranger-ui.local
      secretName: arranger-ui.local
