# Default values for Arranger.
affinity: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

config:
  allowedCorsOrigins: []
  # - https://my-app.example.com

  catalogues: []
  # (Example:)
  # - id: my-catalogue   # DNS label: lowercase alphanumeric and hyphens only
  #   configs:
  #     base:
  #     extended:
  #     facets:
  #     matchbox:
  #     table:

  dev:
    admin: false
    debug: false
    logs: false

  downloadMaxRows: 100
  downloadStreamBufferSize: 2000

  elasticsearch:
    host: http://elasticsearch:9200
    password:
      secretName:
      secretKey: # defaults to the username value when empty
    setsIndex: arranger-sets
    setsType: arranger-sets
    username:
      # if empty or not defined, ES configured without auth

  features:
    allowCustomDownloadMaxRows: false
    disableDownloads: false
    disableFilters: false
    disableGraphqlPlayground: false
    disableSets: false

  graphql:
    # leave empty for no limit
    maxAliases:
    maxDepth:

  maxResultsWindow: 10000
  path: /app/configs
  pingMs: 2200
  probesEndpoint: &probesEndpoint "/ping"
  rowIdFieldName: id
  searchEngine: "" # leave empty to auto-detect from ES/OpenSearch version API
  serverPort: 5050

extraEnv: # placeholder for undetermined custom env vars

fullnameOverride:

image:
  repository: ghcr.io/overture-stack/arranger-search-server
  pullPolicy: Always
  tag: "latest" # Overrides the image tag whose default is the chart appVersion

imagePullSecrets: []

ingress:
  # annotations:
  #   cert-manager.io/cluster-issuer: letsencrypt
  # className: private
  enabled: false
  hosts:
  - host: arranger-server.local
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls:
  - hosts:
    - arranger-server.local
    secretName: arranger-server.local

nameOverride:

nodeSelector: {}

podAnnotations: {}

podSecurityContext:
  runAsGroup: 9999
  runAsNonRoot: true
  runAsUser: 9999

probes:
  liveness:
    path: *probesEndpoint
    initialDelaySeconds: 30
    timeoutSeconds: 2
    periodSeconds: 8
    failureThreshold: 1

  readiness:
    path: *probesEndpoint
    initialDelaySeconds: 60
    timeoutSeconds: 2
    periodSeconds: 3
    failureThreshold: 2

  startup:
    path: *probesEndpoint
    initialDelaySeconds: 60
    timeoutSeconds: 2
    periodSeconds: 3
    failureThreshold: 2

replicaCount: 1

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  portName: arranger-server

serviceAccount:
  create: true
  annotations: {}
  name:
    # If not set and create is true, a name is generated using the fullname template

tolerations: []
