apiVersion: v1

kind: ConfigMap

metadata:
  name: {{ include "arranger.fullname" . }}-server-configs
  labels:
    app.kubernetes.io/name: {{ include "arranger.name" . }}
    helm.sh/chart: {{ include "arranger.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

{{- if .Values.serverConfigs }}
data:
  base.json: |
    {{- include "common.tplvalues.render" ( dict "value" .Values.serverConfigs.baseConfigs "context" $ ) | nindent 4 }}
  extended.json: |
    {{- include "common.tplvalues.render" ( dict "value" .Values.serverConfigs.extendedConfigs "context" $ ) | nindent 4 }}
  facets.json: |
    {{- include "common.tplvalues.render" ( dict "value" .Values.serverConfigs.facetsConfigs "context" $ ) | nindent 4 }}
  matchbox.json: |
    {{- include "common.tplvalues.render" ( dict "value" .Values.serverConfigs.matchboxConfigs "context" $ ) | nindent 4 }}
  table.json: |
    {{- include "common.tplvalues.render" ( dict "value" .Values.serverConfigs.tableConfigs "context" $ ) | nindent 4 }}

immutable: true
{{- end }}

