apiVersion: v1

kind: ConfigMap
metadata:
  name: {{ include "arranger.fullname" . }}-nginx-config
  labels:
    app.kubernetes.io/name: {{ include "arranger.name" . }}
    helm.sh/chart: {{ include "arranger.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  nginx.conf: |-
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {

    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '

                          '"$http_user_agent" "$http_x_forwarded_for"';
        access_log  /var/log/nginx/access.log  main;

        server {
            listen {{ .Values.uiConfig.port }};

            location / {
                root /app/arranger-admin;
                include /etc/nginx/security-headers.conf;
            }

            location /admin/graphql {
                proxy_pass {{ .Values.uiConfig.serverUrl }}/admin/graphql;
                include /etc/nginx/security-headers.conf;
            }
        }
    }
  env-config.template.js: |-
    window.__env__ = {
    REACT_APP_BASE_URL: '{{ .Values.uiConfig.ReactAppBaseURL }}',
    REACT_APP_ARRANGER_ADMIN_ROOT: '/{{ .Values.uiConfig.ReactAppBaseURL }}/admin/graphql'.replace('//', '/'),
    };
