apiVersion: v1

kind: ConfigMap

metadata:
  name: {{ include "arranger.fullname" . }}-server-configs
  labels:
    app.kubernetes.io/name: {{ include "arranger.name" . }}
    helm.sh/chart: {{ include "arranger.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

data:
  {{- $baseConfigs := coalesce .Values.config.components.baseConfigs .Values.baseConfigs -}}
  {{- if $baseConfigs }}
  base.json: |
    {{- include "common.tplvalues.render" ( dict "value" $baseConfigs "context" $ ) | fromYaml | toPrettyJson | nindent 4 }}
  {{- end }}

  {{- $extendedConfigs := coalesce .Values.config.components.extendedConfigs .Values.extendedConfigs -}}
  {{- if $extendedConfigs }}
  extended.json: |
    {{- include "common.tplvalues.render" ( dict "value" $extendedConfigs "context" $ ) | fromYaml | toPrettyJson | nindent 4 }}
  {{- end }}

  {{- $facetsConfigs := coalesce .Values.config.components.facetsConfigs .Values.facetsConfigs -}}
  {{- if $facetsConfigs }}
  facets.json: |
    {{- include "common.tplvalues.render" ( dict "value" $facetsConfigs "context" $ ) | fromYaml | toPrettyJson | nindent 4 }}
  {{- end }}

  {{- $matchboxConfigs := coalesce .Values.config.components.matchboxConfigs .Values.matchboxConfigs -}}
  {{- if $matchboxConfigs }}
  matchbox.json: |
    {{- include "common.tplvalues.render" ( dict "value" $matchboxConfigs "context" $ ) | fromYaml | toPrettyJson | nindent 4 }}
  {{- end }}

  {{- $tableConfigs := coalesce .Values.config.components.tableConfigs .Values.tableConfigs -}}
  {{- if $tableConfigs }}
  table.json: |
    {{- include "common.tplvalues.render" ( dict "value" $tableConfigs "context" $ ) | fromYaml | toPrettyJson | nindent 4 }}
  {{- end }}
