apiVersion: apps/v1

kind: Deployment

metadata:
  name: {{ include "arranger.fullname" . }}
  labels:
    {{- include "arranger.labels" . | nindent 4 }}

spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}

  selector:
    matchLabels:
      {{- include "arranger.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      annotations:
        checksum/config: {{ toJson .Values.config.catalogues | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}

      labels:
        {{- include "arranger.selectorLabels" . | nindent 8 }}

    spec:
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}

      containers:
        - name: server
          env:
            {{- if .Values.config.allowedCorsOrigins }}
            - name: ALLOWED_CORS_ORIGINS
              value: {{ .Values.config.allowedCorsOrigins | join "," }}
            {{- end }}

            - name: ALLOW_CUSTOM_DOWNLOAD_MAX_ROWS
              value: {{ .Values.config.features.allowCustomDownloadMaxRows | quote }}

            - name: CONFIGS_PATH
              value: {{ .Values.config.path }}

            - name: DISABLE_DOWNLOADS
              value: {{ .Values.config.features.disableDownloads | quote }}

            - name: DISABLE_FILTERS
              value: {{ .Values.config.features.disableFilters | quote }}

            - name: DISABLE_GRAPHQL_PLAYGROUND
              value: {{ .Values.config.features.disableGraphqlPlayground | quote }}

            - name: DISABLE_SETS
              value: {{ .Values.config.features.disableSets | quote }}

            - name: DOWNLOAD_MAX_ROWS
              value: {{ .Values.config.downloadMaxRows | quote }}

            - name: DOWNLOAD_STREAM_BUFFER_SIZE
              value: {{ .Values.config.downloadStreamBufferSize | quote }}

            - name: ENABLE_ADMIN
              value: {{ .Values.config.dev.admin | quote }}

            - name: ENABLE_DEBUG
              value: {{ .Values.config.dev.debug | quote }}

            - name: ENABLE_LOGS
              value: {{ .Values.config.dev.logs | quote }}

            - name: ES_ARRANGER_SETS_INDEX
              value: {{ .Values.config.elasticsearch.setsIndex }}

            - name: ES_ARRANGER_SETS_TYPE
              value: {{ .Values.config.elasticsearch.setsType }}

            - name: ES_HOST
              value: {{ .Values.config.elasticsearch.host }}

            {{- if .Values.config.elasticsearch.username }}
            - name: ES_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.elasticsearch.password.secretName }}
                  key: {{ .Values.config.elasticsearch.password.secretKey | default .Values.config.elasticsearch.username }}

            - name: ES_USER
              value: {{ .Values.config.elasticsearch.username }}
            {{- end }}

            {{- if .Values.config.graphql.maxAliases }}
            - name: GRAPHQL_MAX_ALIASES
              value: {{ .Values.config.graphql.maxAliases | quote }}
            {{- end }}

            {{- if .Values.config.graphql.maxDepth }}
            - name: GRAPHQL_MAX_DEPTH
              value: {{ .Values.config.graphql.maxDepth | quote }}
            {{- end }}

            - name: MAX_RESULTS_WINDOW
              value: {{ .Values.config.maxResultsWindow | quote }}

            - name: PING_MS
              value: {{ .Values.config.pingMs | quote }}

            - name: PING_PATH
              value: {{ .Values.config.probesEndpoint }}

            - name: ROW_ID_FIELD_NAME
              value: {{ .Values.config.rowIdFieldName }}

            {{- if .Values.config.searchEngine }}
            - name: SEARCH_ENGINE
              value: {{ .Values.config.searchEngine }}
            {{- end }}

            - name: SERVER_PORT
              value: {{ .Values.config.serverPort | quote }}

          {{- if .Values.extraEnv }}
            {{- range $key, $value := .Values.extraEnv}}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.config.serverPort }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}

          ports:
            - name: {{ .Chart.Name }}-server
              containerPort: {{ .Values.config.serverPort }}
              protocol: TCP

          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.config.serverPort }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}

          startupProbe:
            httpGet:
              path: {{ .Values.probes.startup.path }}
              port: {{ .Values.config.serverPort }}
            initialDelaySeconds: {{ .Values.probes.startup.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.probes.startup.timeoutSeconds }}
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}

          volumeMounts:
            - name: server-user-home-emptydir
              mountPath: /home/node

            - name: server-tmp-emptydir
              mountPath: /tmp

            {{- range .Values.config.catalogues }}
            - name: server-configs-{{ .id }}
              mountPath: {{ $.Values.config.path }}/{{ .id }}
              readOnly: true
            {{- end }}

    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      serviceAccountName: {{ include "arranger.serviceAccountName" . }}

      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

      volumes:
        - name: server-user-home-emptydir
          emptyDir: {}

        - name: server-tmp-emptydir
          emptyDir: {}

        {{- range .Values.config.catalogues }}
        - name: server-configs-{{ .id }}
          configMap:
            name: {{ include "arranger.fullname" $ }}-server-configs-{{ .id }}
        {{- end }}
