apiVersion: apps/v1

kind: Deployment

metadata:
  name: {{ include "arranger.fullname" . }}
  labels:
    {{- include "arranger.labels" . | nindent 4 }}

spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}

  selector:
    matchLabels:
      {{- include "arranger.selectorLabels" . | nindent 6 }}

  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

      labels:
        {{- include "arranger.selectorLabels" . | nindent 8 }}

    spec:
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}

      containers:
        - name: server
          env:
            - name: CONFIG_PATH # route for config files within the container
              value: {{ .Values.config.path }}

            - name: DOCUMENT_TYPE
              value: {{ .Values.config.documentType }}

            - name: DOWNLOAD_STREAM_BUFFER_SIZE
              value: {{ .Values.config.downloadStreamBufferSize | quote }}

            - name: MAX_DOWNLOAD_ROWS
              value: {{ .Values.config.maxDownloadRows | quote }}

            - name: MAX_RESULTS_WINDOW
              value: {{ .Values.config.maxResultsWindow | quote }}

            - name: PING_PATH
              value: {{ .Values.config.pingEndpoint }}

            - name: PORT
              value: {{ coalesce .Values.apiConfig.port .Values.config.port | quote }}

            - name: ROW_ID_FIELD_NAME
              value: {{ .Values.config.rowIdFieldName }}

          # Elasticsearch
            - name: ES_HOST
              value: {{ coalesce .Values.config.elasticsearch.host .Values.apiConfig.es.host }}

            - name: ES_INDEX
              value: {{ .Values.config.elasticsearch.index }}

            {{- if (coalesce .Values.config.elasticsearch.username .Values.apiConfig.es.username) }}
            - name: ES_USER
              value: {{coalesce .Values.config.elasticsearch.username .Values.apiConfig.es.username }}

            - name: ES_PASS
              valueFrom:
                secretKeyRef:
                  name: {{coalesce .Values.config.elasticsearch.password.secretName .Values.apiConfig.es.password.secretName }}
                  key: {{coalesce .Values.config.elasticsearch.username .Values.apiConfig.es.username }}
            {{- end }}

          # dev flags
            - name: DEBUG
              value: {{ .Values.config.dev.debug | quote }}

            - name: ENABLE_ADMIN
              value: {{ .Values.config.dev.admin | quote }}

            - name: ENABLE_LOGS
              value: {{ .Values.config.dev.logs | quote}}

          # extras

          {{- if .Values.apiConfig.extraEnv }}
            {{- range $key, $value := .Values.apiConfig.extraEnv}}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}

          {{- if .Values.extraEnv }}
            {{- range $key, $value := .Values.extraEnv}}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}

          image: "{{ coalesce .Values.apiImage.repository .Values.image.repository }}:{{ coalesce .Values.apiImage.tag .Values.image.tag .Chart.AppVersion }}"

          imagePullPolicy: {{ coalesce .Values.apiImage.pullPolicy .Values.image.pullPolicy }}

          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.config.port }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}

          ports:
            - name: {{ .Chart.Name }}-server
              containerPort: {{ coalesce .Values.apiConfig.port .Values.config.port }}
              protocol: TCP

          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.config.port }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}

          startupProbe:
            httpGet:
              path: {{ .Values.probes.startup.path }}
              port: {{ .Values.config.port }}
            initialDelaySeconds: {{ .Values.probes.startup.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.probes.startup.timeoutSeconds }}
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}

          volumeMounts:
            - name: server-user-home-emptydir
              mountPath: /home/node

            - name: server-tmp-emptydir
              mountPath: /tmp

            - name: server-configs
              mountPath: /app/modules/server/configs/
              readOnly: true

      {{- if .Values.uiConfig.enabled }}
        - name: ui
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.uiImage.repository }}:{{ .Values.uiImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.uiImage.pullPolicy }}

          ports:
            - name: {{ .Chart.Name }}-ui
              containerPort: {{ .Values.uiConfig.port }}
              protocol: TCP

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          env:
            - name: PORT
              value: {{ .Values.uiConfig.port | quote }}
            - name: REACT_APP_ARRANGER_ADMIN_ROOT
              value: {{ .Values.uiConfig.serverUrl }}/admin/graphql
            - name: NGINX_CONF_PATH
              value: /etc/nginx/nginx.conf

          volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf

          - name: nginx-config
            mountPath: /etc/nginx/env-config.js
            subPath: env-config.js

          - name: nginx-cache-emptydir
            mountPath: /var/cache/nginx

          - name: nginx-run-emptydir
            mountPath: /var/run
      {{- end }}

    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      serviceAccountName: {{ include "arranger.serviceAccountName" . }}

      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

      volumes:
        - name: server-user-home-emptydir
          emptyDir: {}

        - name: server-tmp-emptydir
          emptyDir: {}

        - name: server-configs
          configMap:
            name: {{ include "arranger.fullname" . }}-server-configs

      {{- if .Values.uiConfig.enabled }}
        - name: nginx-config
          configMap:
            name: {{ include "arranger.fullname" . }}-nginx-config

        - name: nginx-cache-emptydir
          emptyDir: {}

        - name: nginx-run-emptydir
          emptyDir: {}
      {{- end }}
