{{- if and .Values.uiIngress.enabled .Values.uiConfig.enabled -}}
{{- $fullName := include "arranger.fullname" . -}}
{{- if semverCompare ">=1.19" .Capabilities.KubeVersion.Version }}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14" .Capabilities.KubeVersion.Version }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-ui
  labels:
    {{- include "arranger.labels" . | nindent 4 }}
  {{- with .Values.uiIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.uiIngress.tls }}
  tls:
  {{- range .Values.uiIngress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.uiIngress.host }}
      http:
        paths:
{{- if semverCompare ">=1.19" .Capabilities.KubeVersion.Version }}
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: {{ .Chart.Name }}-ui
{{- else -}}
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ .Chart.Name }}-ui
{{- end }}
{{- end }}
