{{- if .Values.apiIngress.enabled -}}
{{- $fullName := include "arranger.fullname" . -}}
{{- $svcPort := .Values.service.apiPort -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-api
  labels:
    {{- include "arranger.labels" . | nindent 4 }}
  {{- with .Values.apiIngress.annotations }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.apiIngress.tls }}
  tls:
  {{- range .Values.apiIngress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.apiIngress.host }}
      http:
        paths:
          - path: /api/(.*)
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ .Chart.Name }}-api
{{- end }}
