apiVersion: v1
kind: Service
metadata:
  name: {{ include "arranger.fullname" . }}
  labels:
    {{- include "arranger.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ coalesce .Values.service.apiPort .Values.service.port }}
      targetPort: {{ .Chart.Name }}-server
      protocol: TCP
      name: {{ .Chart.Name }}-server

  {{- if .Values.uiConfig.enabled }}
    - port: {{ .Values.service.uiPort }}
      targetPort: {{ .Chart.Name }}-ui
      protocol: TCP
      name: {{ .Chart.Name }}-ui
  {{- end }}

  selector:
    {{- include "arranger.selectorLabels" . | nindent 4 }}

  type: {{ .Values.service.type }}
