apiVersion: v1
kind: Service
metadata:
  name: {{ include "arranger.fullname" . }}
  labels:
    {{- include "arranger.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Chart.Name }}-server
  selector:
    {{- include "arranger.selectorLabels" . | nindent 4 }}
