apiVersion: v1
kind: Service
metadata:
  name: {{ include "arranger.fullname" . }}
  labels:
    {{- include "arranger.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.apiPort }}
      targetPort: {{ .Chart.Name }}-api
      protocol: TCP
      name: {{ .Chart.Name }}-api

    - port: {{ .Values.service.uiPort }}
      targetPort: {{ .Chart.Name }}-ui
      protocol: TCP
      name: {{ .Chart.Name }}-ui
  selector:
    {{- include "arranger.selectorLabels" . | nindent 4 }}
