{{- if .Values.createSecrets }}
{{- range $secretName, $secretConfig := .Values.createSecrets }}
apiVersion: v1
kind: Secret

metadata:
  name: {{ include "stateless-svc.fullname" $ }}-{{ $secretName }}

  labels:
    {{- include "stateless-svc.labels" $ | nindent 4 }}

  {{- with $secretConfig.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

type: {{ $secretConfig.type | default "Opaque" }}

{{- /* TLS secrets */}}
{{- if eq $secretConfig.type "kubernetes.io/tls" }}
  {{- if $secretConfig.data }}
data:
  tls.crt: {{ $secretConfig.data.cert | b64enc }}
  tls.key: {{ $secretConfig.data.key | b64enc }}
  {{- end }}

{{- /* Docker config secrets */}}
{{- else if eq $secretConfig.type "kubernetes.io/dockerconfigjson" }}
  {{- if $secretConfig.data }}
data:
  .dockerconfigjson: {{ $secretConfig.data.dockerconfigjson | b64enc }}
  {{- end }}

{{- /* All other secret types (Opaque, custom, etc.) */}}
{{- else }}
  {{- if $secretConfig.stringData }}
stringData:
    {{- range $key, $value := $secretConfig.stringData }}
  {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}

  {{- if $secretConfig.data }}
data:
    {{- range $key, $value := $secretConfig.data }}
  {{ $key }}: {{ $value | b64enc }}
    {{- end }}
  {{- end }}
{{- end }}

{{- end }}
{{- end }}
