# Default values for ego.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: overture/ego
  tag: latest
  pullPolicy: IfNotPresent

uiImage:
  repository: overture/ego-ui
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  host: ego.local
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

extraEnv: {}

# choose rbac roles to enable
rbac:
  create:
    # for vault kubernetes integration
    tokenReview: true

postgres:
  postgresUsername: postgres
  postgresPassword: password
  postgresDb: ego

appConfig:
  # api configs
  activeProfiles: auth,grpc
  host: ego.local
  googleClientID: ""
  googleClientSecret: ""
  linkedInClientID: ""
  linkedInClientSecret: ""
  githubClientID: ""
  githubClientSecret: ""
  facebookClientID: ""
  facebookClientSecret: ""
  swaggerHost:
  swaggerBaseUrl:
  # ui configs
  egoClientId: ego
