# Default values for ego.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: overture/ego
  tag: 3.0.0
  pullPolicy: IfNotPresent

uiImage:
  repository: overture/ego-ui
  tag: release-3.0.1
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingressApi:
  enabled: false
  host: ego.local
  tls: []

ingressUi:
  enabled: false
  host: ui.ego.local
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

extraEnv: {}

# choose rbac roles to enable
rbac:
  create:
    # for vault kubernetes integration
    tokenReview: true

postgres:
  postgresUsername: postgres
  postgresPassword: password
  postgresDb: ego

appConfig:
  # api configs
  activeProfiles: auth,grpc
  host: ego.local
  googleClientID: ""
  googleClientSecret: ""
  linkedInClientID: ""
  linkedInClientSecret: ""
  githubClientID: ""
  githubClientSecret: ""
  facebookClientID: ""
  facebookClientSecret: ""
  orcidClientID: ""
  orcidClientSecret: ""
  swaggerHost:
  swaggerBaseUrl:
  # ui configs
  egoClientId: ego
  apiTokenDurationDays: "30"
  jwt:
    secret: ""
    userDurationMs: "10800000"
    appDurationMs: "10800000"
  refreshToken:
    durationMs: "43200000"
    cookieIsSecure: ""
