# Default values for ego.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: overture/ego
  tag: 3.5.0
  pullPolicy: IfNotPresent

uiImage:
  repository: overture/ego-ui
  tag: release-3.0.1
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
serviceApi:
  port: http
serviceUi:
  port: http-ui

ingressApi:
  enabled: false
  hosts:
    - host: ego.local
      paths:
        - path: /api/(.*)
          pathType: ImplementationSpecific
  # tls:
  #   - hosts:
  #     - host: ego.local
  # className: private

ingressUi:
  enabled: false
  hosts:
    - host: ui.ego.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  # tls:
  #   - hosts:
  #     - host: ui.ego.local
  # className: private

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

# choose rbac roles to enable
rbac:
  create:
    # for vault kubernetes integration
    tokenReview: true

  psqlSecretName: registry-postgres-postgresql
  databaseUrl: jdbc:postgresql://registry-postgres-postgresql.rdpc-collab-qa:5432/registry


appConfig:
  # api configs
  activeProfiles: auth,grpc
  psqlSecretName: ""
  databaseUrl: ""
  host: ego.local
  keycloakClientID: ""
  keycloakClientSecret: ""
  googleClientID: ""
  googleClientSecret: ""
  linkedInClientID: ""
  linkedInClientSecret: ""
  githubClientID: ""
  githubClientSecret: ""
  facebookClientID: ""
  facebookClientSecret: ""
  orcidClientID: ""
  orcidClientSecret: ""
  swaggerHost:
  swaggerBaseUrl:
  # ui configs
  egoClientId: ego
  apiTokenDurationDays: "30"
  jwt:
    secret: ""
    userDurationMs: "10800000"
    appDurationMs: "10800000"
  refreshToken:
    durationMs: "43200000"
    cookieIsSecure: ""
  defaultProvider: ""
  uiKeycloakEnabled: ""

extraEnv: {}

