# Default values for ego.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/overture-stack/ego
  tag: latest
  pullPolicy: IfNotPresent

uiImage:
  repository: ghcr.io/overture-stack/ego-ui
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
serviceApi:
  port: http
serviceUi:
  port: http-ui

ingressApi:
  # annotations:
  #   cert-manager.io/cluster-issuer: letsencrypt
  # className: private
  enabled: false
  hosts:
    - host: ego.local
      paths:
        - path: /api/(.*)
          pathType: ImplementationSpecific

  # tls:
  #   - hosts:
  #     - ego.local
  #     secretName: ego.local

ingressUi:
  # annotations:
  #   cert-manager.io/cluster-issuer: letsencrypt
  # className: private
  enabled: false
  hosts:
    - host: ui.ego.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  # tls:
  #   - hosts:
  #     - ui.ego.local
  #     secretName: ui.ego.local

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

# choose rbac roles to enable
rbac:
  create:
    # for vault kubernetes integration
    tokenReview: true

  psqlSecretName: registry-postgres-postgresql
  databaseUrl: jdbc:postgresql://registry-postgres-postgresql.rdpc-collab-qa:5432/registry


appConfig:
  # api configs
  activeProfiles: auth,grpc
  psqlSecretName: ""
  databaseUrl: ""
  host: ego.local
  keycloakClientID: ""
  keycloakClientSecret: ""
  googleClientID: 268575437964-n8v6a1mi50tka2klqsb5d38lco0poj74.apps.googleusercontent.com
  googleClientSecret: ""
  googleAuthorizationUri: ""
  linkedInClientID: ""
  linkedInClientSecret: ""
  githubClientID: ""
  githubClientSecret: ""
  facebookClientID: 140524976574963 
  facebookClientSecret: 2439abe7ae008bda7ab5cfdf706b4d66
  orcidClientID: ""
  orcidClientSecret: ""
  swaggerHost:
  swaggerBaseUrl:
  # ui configs
  egoClientId: ego
  apiTokenDurationDays: "30"
  jwt:
    secret: ""
    userDurationMs: "10800000"
    appDurationMs: "10800000"
  refreshToken:
    durationMs: "43200000"
    cookieIsSecure: ""
  defaultProvider: ""
  uiKeycloakEnabled: ""

extraEnv: {}

