apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "muse.fullname" . }}
  labels:
    {{- include "muse.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "muse.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "muse.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "muse.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.appConfig.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.appConfig.port }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.appConfig.port }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          startupProbe:
            httpGet:
              path: {{ .Values.probes.startup.path }}
              port: {{ .Values.appConfig.port }}
            initialDelaySeconds: {{ .Values.probes.startup.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.probes.startup.timeoutSeconds }}
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SERVER_PORT
              value: {{ .Values.appConfig.port | quote }}
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.appConfig.spring.profiles.active | quote }}
            - name: POSTGRES_HOST
              value: {{ .Values.appConfig.postgres.host | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.appConfig.postgres.port | quote }}
            - name: POSTGRES_DATABASE
              value: {{ .Values.appConfig.postgres.database | quote }}
            - name: POSTGRES_USERNAME
              value: {{ .Values.appConfig.postgres.username | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.appConfig.postgres.passwordSecret }}
                  key: postgresql-password
            - name: POSTGRES_MAXPOOLSIZE
              value: {{ .Values.appConfig.postgres.maxPoolSize | quote }}
            - name: AUTH_JWTPUBLICKEYURL
              value: {{ .Values.appConfig.auth.jwtPublicKeyUrl | quote }}
            - name: AUTH_SCOPES_STUDY_PREFIX
              value: {{ .Values.appConfig.auth.scopes.study.prefix | quote }}
            - name: AUTH_SCOPES_STUDY_SUFFIX
              value: {{ .Values.appConfig.auth.scopes.study.suffix | quote }}
            - name: AUTH_SCOPES_SYSTEM
              value: {{ .Values.appConfig.auth.scopes.system | quote }}
            - name: ARIACLIENT_SONGROOTURL
              value: {{ .Values.appConfig.ariaClient.songRootUrl | quote }}
            - name: ARIACLIENT_SCOREROOTURL
              value: {{ .Values.appConfig.ariaClient.scoreRootUrl | quote }}
            - name: ARIACLIENT_TOKENURL
              value: {{ .Values.appConfig.ariaClient.tokenUrl | quote }}
            - name: ARIACLIENT_CLIENTID
              value: {{ .Values.appConfig.ariaClient.clientId | quote }}
            - name: ARIACLIENT_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "muse.fullname" . }}
                  key: ariaclient-clientsecret
            - name: ARIACLIENT_RETRYMAXATTEMPTS
              value: {{ .Values.appConfig.ariaClient.retryMaxAttempts | quote }}
            - name: ARIACLIENT_RETRYDELAYSEC
              value: {{ .Values.appConfig.ariaClient.retryDelaySec | quote }}
            {{- range $i, $value := .Values.appConfig.cors.domainPatterns }}
            - name: CORS_DOMAINPATTERNS_{{$i}}
              value: {{ $value | quote }}
            {{- end }}
            - name: CORS_MAXAGE
              value: {{ .Values.appConfig.cors.maxAge | quote }}
            - name: CODECCONFIG_MAXHEADERSSIZE
              value: {{ .Values.appConfig.codecConfig.maxHeadersSize | quote }}
            - name: SUBMITUPLOAD_MAXINFLIGHT
              value: {{ .Values.appConfig.submitUpload.maxInFlight | quote }}
          {{- if .Values.env }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
