apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "muse.fullname" . }}
  labels:
    {{- include "muse.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "muse.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "muse.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "muse.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.appConfig.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.appConfig.port }}
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 8
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.appConfig.port }}
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 3
            failureThreshold: 2
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SERVER_PORT
              value: {{ .Values.appConfig.port | quote }}
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.appConfig.spring.profiles.active | quote }}
            - name: POSTGRES_HOST
              value: {{ .Values.appConfig.postgres.host | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.appConfig.postgres.port | quote }}
            - name: POSTGRES_DATABASE
              value: {{ .Values.appConfig.postgres.database | quote }}
            - name: POSTGRES_USERNAME
              value: {{ .Values.appConfig.postgres.username | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.appConfig.postgres.passwordSecret }}
                  key: postgresql-password
            - name: AUTH_JWTPUBLICKEYURL
              value: {{ .Values.appConfig.auth.jwtPublicKeyUrl | quote }}
            - name: AUTH_SCOPES_READ_0
              value: {{ .Values.appConfig.auth.scopes.read | quote }}
            - name: AUTH_SCOPES_WRITE_0
              value: {{ .Values.appConfig.auth.scopes.write | quote }}
            - name: SONGSCORECLIENT_SONGROOTURL
              value: {{ .Values.appConfig.songScoreClient.songRootUrl | quote }}
            - name: SONGSCORECLIENT_SCOREROOTURL
              value: {{ .Values.appConfig.songScoreClient.scoreRootUrl | quote }}
            - name: SONGSCORECLIENT_TOKENURL
              value: {{ .Values.appConfig.songScoreClient.tokenUrl | quote }}
            - name: SONGSCORECLIENT_CLIENTID
              value: {{ .Values.appConfig.songScoreClient.clientId | quote }}
            - name: SONGSCORECLIENT_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "muse.fullname" . }}
                  key: songscoreclient-clientsecret
            {{- range $i, $value := .Values.appConfig.cors.domainPatterns }}
            - name: CORS_DOMAINPATTERNS_{{$i}}
              value: {{ $value | quote }}
            {{- end }}
            - name: CORS_MAXAGE
              value: {{ .Values.appConfig.cors.maxAge | quote }}
            - name: CODECONFIG_MAXHEADERSSIZE
              value: {{ .Values.appConfig.codeConfig.maxHeadersSize | quote }}
          {{- if .Values.env }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
