apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "muse.fullname" . }}
  labels:
    {{- include "muse.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "muse.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "muse.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "muse.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.appConfig.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.appConfig.port }}
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 8
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.appConfig.port }}
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 3
            failureThreshold: 2
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SERVER_PORT
              value: {{ .Values.appConfig.port | quote }}
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.appConfig.spring.profiles.active | quote }}
            - name: SPRING_R2DBC_URL
              value: {{ .Values.appConfig.database.r2dbcUrl | quote }}
            - name: SPRING_R2DBC_USERNAME
              value: {{ .Values.appConfig.database.username | quote }}
            - name: SPRING_R2DBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.appConfig.database.passwordSecret }}
                  key: postgresql-password
            - name: SPRING_FLYWAY_URL
              value: {{ .Values.appConfig.database.flywayUrl | quote }}
            - name: SPRING_FLYWAY_USERNAME
              value: {{ .Values.appConfig.database.username | quote }}
            - name: SPRING_FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.appConfig.database.passwordSecret }}
                  key: postgresql-password
            - name: AUTH_JWTPUBLICKEYURL
              value: {{ .Values.appConfig.auth.jwtPublicKeyUrl | quote }}
            - name: SONGSCORECLIENT_SONGROOTURL
              value: {{ .Values.appConfig.songScoreClient.songRootUrl | quote }}
            - name: SONGSCORECLIENT_SCOREROOTURL
              value: {{ .Values.appConfig.songScoreClient.scoreRootUrl | quote }}
          {{- if .Values.env }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
