apiVersion: v1
kind: Secret
metadata:
  name: {{ include "muse.fullname" . }}
  labels:
    app: {{ include "muse.name" . }}
    chart: {{ include "muse.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- if .Values.appConfig.songScoreClient.clientSecret }}
  songscoreclient-clientsecret: {{ .Values.appConfig.songScoreClient.clientSecret | b64enc | quote }}
  {{- else }}
  songscoreclient-clientsecret: {{ randAlphaNum 15 | b64enc | quote }}
  {{- end }}
