{{- $fullName := include "muse.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ include "muse.name" . }}
    chart: {{ include "muse.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- if not (lookup "v1" "secret" .Release.Namespace $fullName) }}
    {{- if .Values.appConfig.ariaClient.clientSecret }}
    ariaclient-clientsecret: {{ .Values.appConfig.ariaClient.clientSecret | b64enc | quote }}
    {{- else }}
    ariaclient-clientsecret: {{ randAlphaNum 15 | b64enc | quote }}
    {{- end }}
  {{- end }}
