apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rollcall.fullname" . }}
  labels:
{{ include "rollcall.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rollcall.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "rollcall.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
    {{- end }}
    {{- with .Values.podSecurityContext }}
      securityContext:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
        {{- if .Values.appConfig }}
          {{ range $key, $value := .Values.appConfig }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
        {{- end }}
        {{- if .Values.extraEnv }}
          {{ range $key, $value := .Values.extraEnv }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
        {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.appConfig.SERVER_PORT }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /swagger-ui.html
              port: http
          readinessProbe:
            httpGet:
              path: /swagger-ui.html
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
